diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=D:/Program Files (x86)/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.email=xuhai@sjfx.com.cn
core.bare=false
core.repositoryformatversion=0
core.filemode=false
core.symlinks=false
core.ignorecase=true
core.logallrefupdates=true
remote.MyGit.url=github.com:hamango/mango.git
remote.MyGit.fetch=+refs/heads/*:refs/remotes/MyGit/*
remote.MyGit.puttykeyfile=C:\Users\许海\.ssh\id_rsa.pub
remote.MyGit.pushurl=github.com:hamango/mango.git
